MenuItem("8 Queens","../games/8queens/index.htm","images/icons/menu/games/8queens.png",0);
MenuItem("A-Blast","../games/ablast.swf","images/icons/menu/games/ablast.png",1);
MenuItem("Air-Hockey","../games/airhockey.swf","images/icons/menu/games/airhockey.png",1);
MenuItem("Animals","../games/animals.swf","images/icons/menu/games/animal.png",1);
MenuItem("Ants","../games/ants.swf","images/icons/menu/games/ants.png",1);
MenuItem("Battlepong","../games/battlepong.swf","images/icons/menu/games/bpong.png",1);
MenuItem("Battleships","../games/battleship.swf","images/icons/menu/games/battleship.png",1);
MenuItem("Blackjack","../games/blackjack.swf","images/icons/menu/games/blackjack.png",1);
MenuItem("Blast Billards","../games/blastbillard.swf","images/icons/menu/games/billards.png",1);
MenuItem("Checkers","../games/checkers.swf","images/icons/menu/games/checkers.png",1);
MenuItem("Chess","../games/chess.swf","images/icons/menu/games/chess.png",1);
MenuItem("Connect 4","../games/connect4.swf","images/icons/menu/games/connect4.png",1);
MenuItem("Country Guess","../games/countryguess/index.htm","images/icons/menu/games/country.png",0);
MenuItem("Hangman","../games/hangman.swf","images/icons/menu/games/hangman.png",1);
MenuItem("Lines","../games/lines.swf","images/icons/menu/games/lines.png",1);
MenuItem("Memory","../games/memory.swf","images/icons/menu/games/memory.png",1);
MenuItem("Mind Reader","../games/mindreader/index.htm","images/icons/menu/games/mind.PNG",0);
MenuItem("Minesweeper","../games/minesweeper.swf","images/icons/menu/games/minesweeper.png",1);
MenuItem("Package","../games/package.swf","images/icons/menu/games/package.png",1);
MenuItem("Poker","../games/poker.swf","images/icons/menu/games/poker.png",1);
MenuItem("Pong!","../games/pong/index.htm","images/icons/menu/games/pong.png",0);
MenuItem("Portaball","../games/portaball.swf","images/icons/menu/games/breakout.png",1);
MenuItem("Question?","../games/mindread/index.htm","images/icons/menu/games/mind2.PNG",0);
MenuItem("Reflex Test","../games/reflex/index.htm","images/icons/menu/games/reflex.png",0);
MenuItem("Reversi","../games/reversi.swf","images/icons/menu/games/reversi.png",1);
MenuItem("Snake","../games/snake.swf","images/icons/menu/games/snake.png",1);
MenuItem("Solitare","../games/solitare.swf","images/icons/menu/games/solitare.png",1);
MenuItem("Squares","../games/squares.swf","images/icons/menu/games/squares.png",1);
MenuItem("Sudoku","../games/sudoku.swf","images/icons/menu/games/sudoku.png",1);
MenuItem("Telescope","../games/telescope.swf","images/icons/menu/games/telescope.png",1);
MenuItem("Tetris","../games/tetris.swf","images/icons/menu/games/tetris.png",1);
MenuItem("Tic Tac Toe","../games/tictactoe.swf","images/icons/menu/games/tictactoe.png",1);
MenuItem("Towers of Hanoi","../games/hanoi.swf","images/icons/menu/games/hanoi.png",1);
MenuItem("Yahtzee","../games/yahtzee.swf","images/icons/menu/games/yahtzee.png",1);

// Do not edit below this line
createMenu("Games","MenuGames","/icons/mainmenu/games.png");